#!/bin/bash
# Copies solrconfig.xml and schema.xml files in each dev core to their test and prod cores
/bin/cp solr/blacklight-dev-core/conf/solrconfig.xml solr/blacklight-test-core/conf/solrconfig.xml
/bin/cp solr/blacklight-dev-core/conf/solrconfig.xml solr/blacklight-prod-core/conf/solrconfig.xml
/bin/cp solr/blacklight-dev-core/conf/schema.xml solr/blacklight-test-core/conf/schema.xml
/bin/cp solr/blacklight-dev-core/conf/schema.xml solr/blacklight-prod-core/conf/schema.xml
/bin/cp solr/hydra-dev-core/conf/solrconfig.xml solr/hydra-test-core/conf/solrconfig.xml
/bin/cp solr/hydra-dev-core/conf/solrconfig.xml solr/hydra-prod-core/conf/solrconfig.xml
/bin/cp solr/hydra-dev-core/conf/schema.xml solr/hydra-test-core/conf/schema.xml
/bin/cp solr/hydra-dev-core/conf/schema.xml solr/hydra-prod-core/conf/schema.xml